name: ahm-back
dependencies:
  - pip
  - pip:
    - alembic==1.0.11
    - Flask==1.0.2
    - Flask-Login==0.4.1
    - Flask-Migrate==2.5.2
    - Flask-SQLAlchemy==2.4.0
    - Flask-WTF==0.14.2
    - psycopg2-binary==2.8.3
    - SQLAlchemy==1.3.6

