name: ahm-back
dependencies:
  - pip
  - pip:
    - alembic==1.0.11
    - Flask==1.0.2
    - Flask-Mail==0.9.1
    - Flask-Login==0.4.1
    - Flask-Migrate==2.5.2
    - Flask-SQLAlchemy==2.4.0
    - Flask-WTF==0.14.2
    - psycopg2-binary==2.8.3
    - SQLAlchemy==1.3.6
    - SQLAlchemy-serializer==1.3.1
    - python-dateutil<2.8.1
    - botocore==1.13.38
    - boto3==1.10.29
    - simplejson==3.17.0

