"""empty message

Revision ID: 0f779a440372
Revises: f2501838389d
Create Date: 2019-11-20 22:32:13.822152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f779a440372'
down_revision = 'f2501838389d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geographic_attributes', 'attribute_value_type',
               existing_type=postgresql.ENUM('percent', 'count', name='attribute_value_type'),
               nullable=True)
    op.create_unique_constraint('_attribute_year_dataset_uc', 'geographic_attributes', ['geo_code_id', 'attribute_name', 'attribute_year', 'dataset_id'])
    op.add_column('maps', sa.Column('attribute_name_1', sa.Text(), nullable=False))
    op.add_column('maps', sa.Column('attribute_name_2', sa.Text(), nullable=True))
    op.add_column('maps', sa.Column('attribute_year_1', sa.SmallInteger(), nullable=False))
    op.add_column('maps', sa.Column('attribute_year_2', sa.SmallInteger(), nullable=True))
    op.create_unique_constraint('_title_owner_uc', 'maps', ['title', 'owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_title_owner_uc', 'maps', type_='unique')
    op.drop_column('maps', 'attribute_year_2')
    op.drop_column('maps', 'attribute_year_1')
    op.drop_column('maps', 'attribute_name_2')
    op.drop_column('maps', 'attribute_name_1')
    op.drop_constraint('_dataset_attribute-name_uc', 'geographic_attributes', type_='unique')
    op.alter_column('geographic_attributes', 'attribute_value_type',
               existing_type=postgresql.ENUM('percent', 'count', name='attribute_value_type'),
               nullable=False)
    # ### end Alembic commands ###
