"""empty message

Revision ID: 23bc0d09a0b6
Revises: 0f779a440372
Create Date: 2019-12-03 21:37:02.327310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bc0d09a0b6'
down_revision = '0f779a440372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('maps', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
