"""empty message

Revision ID: 409be3b9adca
Revises: 6cc773a052d3
Create Date: 2019-12-10 22:51:06.549738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409be3b9adca'
down_revision = '6cc773a052d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('geographic_dataset_favorites_geographic_dataset_id_fkey', 'geographic_dataset_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'geographic_dataset_favorites', 'geographic_datasets', ['geographic_dataset_id'], ['geographic_dataset_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'geographic_dataset_favorites', type_='foreignkey')
    op.create_foreign_key('geographic_dataset_favorites_geographic_dataset_id_fkey', 'geographic_dataset_favorites', 'maps', ['geographic_dataset_id'], ['map_id'])
    # ### end Alembic commands ###
