"""empty message

Revision ID: 6cc773a052d3
Revises: 66ee0c859f7f
Create Date: 2019-12-05 16:26:08.517070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc773a052d3'
down_revision = '66ee0c859f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geographic_attributes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geographic_attributes', 'deleted_at')
    # ### end Alembic commands ###
