"""empty message

Revision ID: b16bc6f503bb
Revises: 409be3b9adca
Create Date: 2019-12-13 08:49:15.332407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16bc6f503bb'
down_revision = '409be3b9adca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geographic_attributes', sa.Column('fips_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geographic_attributes', 'fips_code')
    # ### end Alembic commands ###
