"""empty message

Revision ID: e49923ba934e
Revises: fca4847f9c60
Create Date: 2019-09-05 09:43:40.771923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e49923ba934e'
down_revision = 'fca4847f9c60'
branch_labels = None
depends_on = None


def upgrade():
    attribute_value_type = postgresql.ENUM('percent', 'count', name='attribute_value_type')
    attribute_value_type.create(op.get_bind())

    op.create_table('email_authentication_codes',
    sa.Column('email_authentication_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('authentication_code', sa.Integer(), nullable=False),
    sa.Column('expiration_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('email_authentication_id')
    )
    op.create_table('geographic_dataset_views',
    sa.Column('geographic_dataset_view_id', sa.Integer(), nullable=False),
    sa.Column('geographic_dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['geographic_dataset_id'], ['maps.map_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('geographic_dataset_view_id')
    )
    op.create_table('map_views',
    sa.Column('map_view_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.map_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('map_view_id')
    )
    op.add_column('geo_codes', sa.Column('fips_code', sa.Text(), nullable=True))
    op.add_column('geographic_attributes', sa.Column('attribute_value_type', sa.Enum('percent', 'count', name='attribute_value_type'), nullable=False))
    op.add_column('geographic_attributes', sa.Column('attribute_year', sa.SmallInteger(), nullable=True))
    op.add_column('geographic_datasets', sa.Column('display_by_default', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('geographic_datasets', sa.Column('organization', sa.Text(), nullable=True))
    op.add_column('geographic_datasets', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('maps', sa.Column('map_thumbnail_link', sa.Text(), nullable=True))
    op.add_column('maps', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'updated_at')
    op.drop_column('maps', 'map_thumbnail_link')
    op.drop_column('geographic_datasets', 'url')
    op.drop_column('geographic_datasets', 'organization')
    op.drop_column('geographic_datasets', 'display_by_default')
    op.drop_column('geographic_attributes', 'attribute_year')
    op.drop_column('geographic_attributes', 'attribute_value_type')
    op.drop_column('geo_codes', 'fips_code')
    op.drop_table('map_views')
    op.drop_table('geographic_dataset_views')
    op.drop_table('email_authentication_codes')
    # ### end Alembic commands ###

    attribute_value_type = postgresql.ENUM('percent', 'count', name='attribute_value_type')
    attribute_value_type.create(op.get_bind())
